### ISSUE TITLE
中文版文档正式上线  www.tagui.com.cn - TagUI Chinese guide & repo gone live

### ISSUE THREAD

**Issue by kangyiwen** [aisingapore/TagUI#1229]
在中国，网上可以访问前需要政府备案，目前已经完成，中文版文档已经上线：[http://www.tagui.com.cn/](http://www.tagui.com.cn/)

源代码地址：[https://gitee.com/TagUIcn/tagui](https://gitee.com/TagUIcn/tagui)
内容我会逐步完善。

希望可以聚集一些中国用户，让TagUI更适合中国环境。

**Comment by kangyiwen** [comment]
@ruthtxh @kensoh  谢谢你们~

**Comment by kensoh** [comment]
Oh wonderful news! Thanks @kangyiwen for sharing this with the Chinese market 🚀💥

I think @ruthtxh and AI Singapore has plans to stop the weekly Zoom calls. Maybe 中文 menu item can be used to replace the Zoom link, and link to your usage guide at http://www.tagui.com.cn. Just an idea.. Ultimately will be up to Ruth where to place the link, so Chinese users can easily choose and view the Chinese documentation on your website.

**Comment by kangyiwen** [comment]
谢谢，昨天上线后 就有2个程序员开始询问我如何使用，而且是商用客户。
如果遇到复杂问题，我会到这里来问你们。
遇到英语好的用户，我也会直接推荐 github 地址给对方。

**Comment by kensoh** [comment]
Oh that is wonderful news to hear! I wish you success in your RPA business in China, Yi Wen.

**Comment by ruthtxh** [comment]
Hi @kangyiwen thanks for letting us know and all the best! 👍

**Comment by kangyiwen** [comment]
谢谢，谢谢。

等 TagUI 有了新的 EXE 安装文件，我开始做点基础视频教程。

**Comment by kensoh** [comment]
If that's ok, Yi Wen and Ruth, I'll suggest keeping the issue open.

Since this has 2 benefits -
- there is still outstanding action to link from TagUI GitHub (or usage guide page or both)
- Chinese users who are viewing the issues page can see this and visit your website

**Comment by kangyiwen** [comment]
有道理，留个中文帖子，更方便中文用户。  谢谢

**Comment by kensoh** [comment]
Hi @kangyiwen, recently @ruthtxh has removed the Zoom link in the GitHub page. That makes suitable space to link to your Chinese site (see below). Hi @ruthtxh I believe Yi Wen's site is sufficiently updated enough to be linked from TagUI GitHub page. I have taken the initiative to link to his page from the GitHub header section (see below). However, please roll back if you or AISG feels that this is still pre-mature. Usually I recommend promoting user's work loudly so that users become successful. When community of users become successful, TagUI will naturally be a successful project.

![Screenshot 2022-05-21 at 1 03 53 AM](https://user-images.githubusercontent.com/10379601/169626102-51c14da6-f59a-457f-ab24-e26b682acc20.png)

**Comment by kensoh** [comment]
@kangyiwen 以上希望助你一臂之力，也让TagUI更完善更强大。

**Comment by kensoh** [comment]
Adding on, I think it is important to link to Yi Wen's website from TagUI official GitHub or usage guide.

This adds credibility that his site and usage guide is legit, and not someone trying to be an imposter site.

**Comment by kensoh** [comment]
@kangyiwen, also, added in credit section of GitHub page - https://github.com/kelaberetiv/TagUI#credits

In my view, the scope, intensity and potential of the contribution is no less of other contributors there.

@ruthtxh, again, please roll back if you find this pre-mature. I would think it's suitably ready to be marketed.

![Screenshot 2022-05-21 at 1 42 45 AM](https://user-images.githubusercontent.com/10379601/169627692-1c80c501-f0ed-4053-8d1e-79b6793ea159.png)

**Comment by kensoh** [comment]
Finally, one more. This way, a Chinese user cannot miss this. At beginning, centre, end of GitHub page all have links.

Fyi @kangyiwen, and again @ruthtxh please roll back if you or AISG finds this pre-mature. I commit first to execute fast.

![Screenshot 2022-05-21 at 2 03 43 AM](https://user-images.githubusercontent.com/10379601/169628490-ee5c7ff9-d8e9-4e93-9b3f-55651fd2e7c5.png)

**Comment by kensoh** [comment]
以上最后一着，画龙点睛

**Comment by kensoh** [comment]
Fyi @ruthtxh there should be no conflict of interests because any downloads are still measured in the same way since Yi Wen links to the usual zip files hosted on TagUI GitHub releases. In future, if there is a need to host elsewhere (due to access limitations to GitHub from China), further changes can be considered and made to still tally the numbers.

**Comment by kangyiwen** [comment]
哈！谢谢 @kensoh  也要谢谢 @ruthtxh ，是你们的一个个回答，让我对 TagUI 越来越有信心。

我用 TagUI 开发的速度，已经比之前快了非常多，感觉思路清晰起来，学到一点就会记录并更新到中文网上，感觉还有很多细节需要学习，这些要在实际项目中遇到才会成长。

对 TagUI 中国区的发展，还有很多想法，但当务之急我还是要更多的深入了解 TagUI，以应对未来中国区的用户问题，总感觉自己掌握的还不够，加油！

**Comment by kensoh** [comment]
别担心，成功并不基于absolute strength, 而是基于relative strength, at the point of impact. 只要你比第二选择好，比客户懂得多，即使没达到完美，客户还是会偏向你。

**Comment by kensoh** [comment]
十万兵马，选择性击中要害，还是可以赢百万大军。

**Comment by twinyk** [comment]
所以说要让真市场来检验，而不是臆想的方向。

发件人: Ken Soh
发送时间: 2022年5月21日 9:51
收件人: kelaberetiv/TagUI
抄送: Subscribed
主题: Re: [kelaberetiv/TagUI] 中文版文档正式上线 www.tagui.com.cn - TagUI Chinese usage guide gone live (Issue #1229)

十万兵马，选择性击中要害，还是可以赢百万大军。

**Comment by kensoh** [comment]
语无伦次

**Comment by ruthtxh** [comment]
Hi @kangyiwen @kensoh I don't see an issue linking the website on our GitHub page, let me check with my other colleagues.

**Comment by kensoh** [comment]
PS - side chat that people who think that crypto and Bitcoin are decentralised are misunderstanding the whole thing. While Bitcoin as a technology is decentralised, the platforms that make it possible to be traded are all centralised (the crypto exchanges). So, in their current form, they are still not solutions to decentralise financial accessibility and power.

**Comment by kangyiwen** [comment]
开源项目，更多是兴趣驱动。跟着tagui，一起成长~

**Comment by kangyiwen** [comment]
Hi 两位~  

中文站上线半年了，目前流量情况是这样，比前阵子有点提升。目前加企交流群的已经超过100人
![image](https://user-images.githubusercontent.com/76672577/197111427-d75f089c-e515-41ef-b44e-5cf333f36623.png)
![image](https://user-images.githubusercontent.com/76672577/197111644-945f13d7-f389-4473-9b8c-826b424b611c.png)


目前遇到比较多的情况是：因为不是EXE安装的，造成很多小问题，希望可以升级一个版本EXE。

另外发现，其实很多 LINUX  和  mac用户，在找RPA产品。

**Comment by kensoh** [comment]
Thanks Yi Wen for sharing these updates! I recall that Ruth has previously packaged everything as .exe and provided that as an option to install for Windows. That seems to be removed, maybe for technical or strategic reasons. Maybe @ruthtxh could share more.

For the Python rpa package that I'm maintaining (actually not doing anything since it is quite stable), it is growing well and having good traffic. And seems to be doing well relative to other open-source RPA offerings such as Robocorp or OpenRPA, at least in terms of stars. However, we are sort of competing in different markets. The rpa package is more for your everyday user who likes to use Python, for decentralised deployment by individuals. Whereas Robocorp / OpenRPA are targetting enterprise users pursuing centralised deployment mode, deploying centrally.

**Comment by kensoh** [comment]
Closing but please ping back if this is still relevant or an issue.
