### ISSUE TITLE
Can't find element in a frame

### ISSUE THREAD

**Issue by gallex** [aisingapore/TagUI#1292]
when I use : 
···
frame id_of_frame 
     click xpath 
```
result :  ERROR - cannot find  xpath

but when I use live mode, it 's OK, very strange: 
```
frame id_of_frame
     live 
``` 
when entry live mode,  I type `click XPATH` , it's OK。

**Comment by ruthtxh** [comment]
Hi @gallex you cannot use frame step in live mode, so I would assume the element is not nested within a frame? Another thing to check if XPath can be clicked in live mode but not at run time is to dock your chrome dev tools on a separate popup instead of docking to the side because sometimes when docking to the side, the responsiveness of the page causes the XPath of the element to change.

**Comment by gallex** [comment]
> Hi @gallex you cannot use frame step in live mode, so I would assume the element is not nested within a frame? 

Yes, I can't direct step in live mode, but if I add live directive after frame directive is seems OK, is it right ?.  I'm very sure the element is in  a frame ,  because I had try find that element in root,  it no exists yet.

**Comment by ruthtxh** [comment]
Hi @gallex the live step is independent of the frame step. Could you share the webpage or the html of page for us to take a look?

**Comment by kensoh** [comment]
Closing but please ping back if this is still relevant or an issue.
