### ISSUE TITLE
离线部署时在应用OCR识别时遇到问题。- try using original TagUI zip or installer

### ISSUE THREAD

**Issue by shusukui** [aisingapore/TagUI#1359]
由于项目要求，应用环境不允许联网，在部署TagUI时需要应用OCR功能，click 指令后跟图片文件，但启动tag文件时遇到错误。如图片所示。请问如何解决。
![微信图片_20230921142729](https://github.com/aisingapore/TagUI/assets/8498055/e9e7d01a-dd2f-4e97-a2cc-2f344cee8f0a)

**Comment by woshizhoujiafu** [comment]
没有装JDK

**Comment by kensoh** [comment]
Hi @shusukui how do you download and install TagUI? If you get from https://tagui.readthedocs.io/en/latest/setup.html it will have this file. But this error will show the first time it runs while it auto-configures SikuliX's dependency.

If you run and try to zip up tagui locally to copy to another PC you will get this error because that dependency is moved away by SikuliX. Try to copy using above original TagUI zip file.

**Comment by kensoh** [comment]
Also tagging @woshizhoujiafu
