### ISSUE TITLE
[RPA][ERROR] - TagUI process ended unexpectedly  - ERROR - undefined is not an object (evaluating 'e.message.charAt')

### ISSUE THREAD

**Issue by KateKrechet** [aisingapore/TagUI#1364]
Hi!
Yesterday I installed targui - https://tagui.readthedocs.io/en/latest/setup.html.
When I launched the sample.py from github - I get an error - undefined is not an object (evaluating 'e.message.charAt').
rpa_python.log located below:

START - automation started - Wed Nov 15 2023 11:15:07 GMT+0300 (RTZ 2 (зима))

LIVE MODE - type done to quit
 [RPA][STARTED]
[RPA][0] - listening for inputs
[RPA][1] - https://ca.yahoo.com
[RPA][1] - listening for inputs
[RPA][2] - exist_result = exist('ybar-sbq').toString()
[RPA][2] - listening for inputs
[RPA][3] - dump exist_result to rpa_python.txt
ERROR - undefined is not an object (evaluating 'e.message.charAt')

https://ca.yahoo.com/ - Yahoo | Mail, Weather, Search, News, Finance, Sports, Shopping, Entertainment, Video
FINISH - automation finished - 24.3s

**Comment by blandyy** [comment]
Hello, did you find the answer to this question? I alleviated this problem by modifying the source code, but I couldn't find the cause of the problem. The modification method is to modify tagui in the directory of tagui_ Delete all e.message.charAt in parse.php for a total of two errors, so that the errors it captures do not need to reference the e object. I also look forward to you truly solving this problem.

**Comment by kensoh** [comment]
Hi @KateKrechet and @blandyy the rpa package is a Python version of TagUI you cannot run sample.py using this human language version of TagUI. That is only to be used with Python rpa package.
