### ISSUE TITLE
How to customize a command in TagUI by modifying the source - check this

### ISSUE THREAD

**Issue by supercena** [aisingapore/TagUI#1402]

**Comment by kensoh** [comment]
Hi @supercena for technical documentation, check this section for developers and which file for what purpose. 

https://github.com/aisingapore/TagUI/tree/pre_v6?tab=readme-ov-file#developers-reference

For video walk through of TagUI architecture, see this video series - 

https://www.youtube.com/watch?v=oq8HlJujraE

It might be hard for you to make changes to it because change often has to be done both in tagui_parse.php and tagui_header.js

**Comment by supercena** [comment]
ok thanks
